### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by priyanshrastogi** [Breeze18/Breeze#1]
1.  Create Models:
User: username/email, name, password, college, gender, age, phone.
You can use django.contrib.auth.models.User to create this. This automatically handles the auth. We can use username field for email. For additional fields, you can make an additional model i.e. UserProfile. It will have additional fields like college, gender, phone etc. Then make a one-to-one relation between User and UserProfile.
 
Event: name, description, category, subcategory, club, contact_persons
Everything is in the string format. So you can use CharField for all except description. For description, we can use TextField.

Registration: event_id, user_id, mapper, transaction_id.

FormData: name, age, gender

mapper field in registration maps event form data for each event.

**Comment by HalfMomentum** [comment]
todo : Complete.
see [commit](https://github.com/Breeze18/Breeze/commit/0635cd9a121dce70839ac3286099a371fe252ddf)
